### ISSUE TITLE
Remove unnecessary  (*) for fields that not required

### ISSUE THREAD

**Issue by Ge6ben** [QuickBlox/q-consultation#27]
Hi Team,
I have a small concern: the `login` field is not required but has ( * ) !

<img width="1188" alt="Screenshot 2024-11-19 at 6 08 02 PM" src="https://github.com/user-attachments/assets/7d235e4d-1018-4fc0-9e00-b52fd30b5c98">

**Comment by andrii-khomutovskyi** [comment]
Hi @Ge6ben 
In the system, one of the fields must be filled in: Email or Login, so they are both marked as (`*`)

**Comment by Ge6ben** [comment]
@andrii-khomutovskyi-qb, so it's required if validation! now make sense 
Thanks
