### ISSUE TITLE
422 | "[QuickBlox] base Forbidden. Need user."

### ISSUE THREAD

**Issue by Ge6ben** [QuickBlox/q-consultation#28]
Hi I am new to the QuickBlox
I just followed the [video that was added in docs](https://www.youtube.com/watch?v=-nEoba8vq_I&t=545s) 
But I couldn't continue due to getting this error when I tried to start the chat 
Response:
```
{
    "statusCode": 422,
    "error": "Unprocessable Entity",
    "message": "[QuickBlox] base Forbidden. Need user."
}
```
Payload
```
{
    "client_id": 140521582,
    "provider_id": 140518423,
    "description": "HI LET's do it!"
}
```

<img width="1312" alt="Screenshot 2024-11-20 at 1 16 55 PM" src="https://github.com/user-attachments/assets/0cd1bd04-8274-47d1-8b4a-3c50f7aafd06">

Also Already add user in the dashboard!

**Comment by andrii-khomutovskyi** [comment]
@Ge6ben This video is outdated, please use the steps described on this page: [https://quickblox.github.io/q-consultation/dev/quick-start](https://quickblox.github.io/q-consultation/dev/quick-start)

**Comment by Ge6ben** [comment]
@andrii-khomutovskyi-qb  thank you will do

**Comment by Ge6ben** [comment]
Hi @andrii-khomutovskyi-qb, I followed the page but got this error
when i run 
`yarn init:schema`
```
(node:25816) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
lerna notice cli v7.2.0
lerna notice filter including "@qc/bin"
lerna info filter [ '@qc/bin' ]

> @qc/bin:"init:schema"

(node:25816) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
QuickBlox account owner credentials found in config file: /Users/lara/WebstormProjects/q-consultation/.env
Error:
undefined

```
<img width="1312" alt="Screenshot 2024-11-21 at 1 42 23 PM" src="https://github.com/user-attachments/assets/f7d6b5e8-5705-4bc3-acd3-bdc98b4dba45">


I am using 
```
node 22.11.0
yarn  3.6.3
```
System:
```
MacBook Pro
```
Browser:
```
Google Chrome
```

### Also, I used my own email, not with Google or another SSO


This my env file
```
QB_SDK_CONFIG_APP_ID=*****
QB_SDK_CONFIG_AUTH_KEY="ak_*******"
QB_SDK_CONFIG_AUTH_SECRET="*****"
QB_SDK_CONFIG_ACCOUNT_KEY="******"
QB_SDK_CONFIG_DEBUG=false
QB_SDK_CONFIG_ENDPOINT_API="api.quickblox.com"
QB_SDK_CONFIG_ENDPOINT_CHAT="chat.quickblox.com"
QB_SDK_CONFIG_ICE_SERVERS=
QB_ADMIN_EMAIL="*********"
QB_ADMIN_PASSWORD="*******"
BEARER_TOKEN=""
OPENAI_API_KEY=""
AI_QUICK_ANSWER=false
AI_SUGGEST_PROVIDER=false
AI_RECORD_ANALYTICS=false
AI_REPHRASE=false
AI_TRANSLATE=false
PROVIDER_ASSISTANT_ID=-1
APP_NAME="Q-Consultation"
APP_DESCRIPTION="Q-Consultation"
ENABLE_REDUX_LOGGER=false
DISPLAY_VERSION=false
CLIENT_APP_URL="https://127.0.0.1:3001"
SERVER_APP_URL="http://127.0.0.1:4000"
ENABLE_GUEST_CLIENT=false
HAS_HISTORY=false
HAS_PROVIDER_LIST=false
HAS_CHANGE_LANGUAGE=false
DEFAULT_LANGUAGE="en"
FILE_SIZE_LIMIT=10485760
FILE_EXTENSIONS_WHITELIST="gif jpeg jpg mov mp4 png csv docx pdf pptx txt xls xlsx zip webm heic heif"

```

**Comment by andrii-khomutovskyi** [comment]
Hi @Ge6ben 
I think your app already has the required custom object schemas, that's why you get the error.

If you are not sure about the correctness of the existing schemas in [QuickBlox](https://admin.quickblox.com), I advise you to delete them and retry the command. 
If you have problems with this command, you can use other methods of uploading schemas described in https://quickblox.github.io/q-consultation/dev/setup-and-deployment/configurations/#upload-schema

**Comment by Ge6ben** [comment]
Hi @andrii-khomutovskyi-qb, I deleted the app and tried from scratch, it works now Thanks, man 🙌🏿🔥
