### ISSUE TITLE
Vue js | How do I integrate  my  existing vue js project with q-consultations ?

### ISSUE THREAD

**Issue by Ge6ben** [QuickBlox/q-consultation#29]
Hi team!
I am coming from Vue js frameworks and struggling with finding resources on how to integrate my existing projects with q-consultations.? I see, there are a few examples that are not with react or vue that help me to be inspired! 
[Links](https://github.com/QuickBlox/q-consultation/tree/master/apps/integration-pages)

Also, I have a few concerns about how I integrate my existing authentication with q-consultation ? as I see, it has its own authentications page, of course  the user should not  log in twice!

**Comment by andrii-khomutovskyi** [comment]
Hi @Ge6ben
To use the application you need to have a user.
You can use [Custom Identity Provider](https://docs.quickblox.com/docs/custom-identity-provider) to combine your own users and QuickBlox users, or you can create users in QConsultation yourself using API.

API: https://quickblox.github.io/q-consultation/api

Once you have logged in using the API, and have your QuickBlox session token, you can pass it to the QConsultation application URL and thus log in to the application without having to re-enter your email address and password.

Routes:
- `https://client-qc-website.com/[pathname]?token=[session_token]`
- `https://provider-qc-website.com/[pathname]?token=[session_token]`

> `[pathname]` is the path to a specific Q-Consultation page
> `[session_token]` is the token from session ([Session Model](https://docs.quickblox.com/reference/session-model))

**Comment by Ge6ben** [comment]
Hi @andrii-khomutovskyi-qb, thank you it's clear
